version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - kafka
    networks:
      - default
    environment:
      GRPC_PORT: 9091
      HTTP_PORT: 8080
      DB_HOST: blah
      DB_USER: dev
      DB_PASSWORD: dev-user5
      DB_SCHEMA: checkout
      CATALOG_ADDRESS: host.docker.internal:9090

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    restart: unless-stopped
    logging:
      driver: none
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - default

  kafka:
    image: confluentinc/cp-kafka:latest
    restart: unless-stopped
    depends_on:
      - zookeeper
    logging:
      driver: none
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    networks:
      - default