// Code generated by protoc-gen-go. DO NOT EDIT.
// source: checkout.proto

package checkout

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	BuyerId              string   `protobuf:"bytes,2,opt,name=buyer_id,json=buyerId,proto3" json:"buyer_id,omitempty"`
	AccountId            string   `protobuf:"bytes,3,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Token                string   `protobuf:"bytes,5,opt,name=token,proto3" json:"token,omitempty"`
	BuyerEmail           string   `protobuf:"bytes,6,opt,name=buyer_email,json=buyerEmail,proto3" json:"buyer_email,omitempty"`
	Api                  string   `protobuf:"bytes,7,opt,name=api,proto3" json:"api,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_a95bdbc7e39fe4fd, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Request) GetBuyerId() string {
	if m != nil {
		return m.BuyerId
	}
	return ""
}

func (m *Request) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *Request) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *Request) GetBuyerEmail() string {
	if m != nil {
		return m.BuyerEmail
	}
	return ""
}

func (m *Request) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

type Request_Card struct {
	CardNum              int32    `protobuf:"varint,1,opt,name=card_num,json=cardNum,proto3" json:"card_num,omitempty"`
	DateM                string   `protobuf:"bytes,2,opt,name=date_m,json=dateM,proto3" json:"date_m,omitempty"`
	DateY                string   `protobuf:"bytes,3,opt,name=date_y,json=dateY,proto3" json:"date_y,omitempty"`
	Code                 int32    `protobuf:"varint,4,opt,name=code,proto3" json:"code,omitempty"`
	First                string   `protobuf:"bytes,5,opt,name=first,proto3" json:"first,omitempty"`
	Last                 string   `protobuf:"bytes,6,opt,name=last,proto3" json:"last,omitempty"`
	Zip                  int32    `protobuf:"varint,7,opt,name=zip,proto3" json:"zip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request_Card) Reset()         { *m = Request_Card{} }
func (m *Request_Card) String() string { return proto.CompactTextString(m) }
func (*Request_Card) ProtoMessage()    {}
func (*Request_Card) Descriptor() ([]byte, []int) {
	return fileDescriptor_a95bdbc7e39fe4fd, []int{0, 0}
}

func (m *Request_Card) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request_Card.Unmarshal(m, b)
}
func (m *Request_Card) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request_Card.Marshal(b, m, deterministic)
}
func (m *Request_Card) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request_Card.Merge(m, src)
}
func (m *Request_Card) XXX_Size() int {
	return xxx_messageInfo_Request_Card.Size(m)
}
func (m *Request_Card) XXX_DiscardUnknown() {
	xxx_messageInfo_Request_Card.DiscardUnknown(m)
}

var xxx_messageInfo_Request_Card proto.InternalMessageInfo

func (m *Request_Card) GetCardNum() int32 {
	if m != nil {
		return m.CardNum
	}
	return 0
}

func (m *Request_Card) GetDateM() string {
	if m != nil {
		return m.DateM
	}
	return ""
}

func (m *Request_Card) GetDateY() string {
	if m != nil {
		return m.DateY
	}
	return ""
}

func (m *Request_Card) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Request_Card) GetFirst() string {
	if m != nil {
		return m.First
	}
	return ""
}

func (m *Request_Card) GetLast() string {
	if m != nil {
		return m.Last
	}
	return ""
}

func (m *Request_Card) GetZip() int32 {
	if m != nil {
		return m.Zip
	}
	return 0
}

type Response struct {
	State                string   `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	Api                  string   `protobuf:"bytes,2,opt,name=api,proto3" json:"api,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_a95bdbc7e39fe4fd, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *Response) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func init() {
	proto.RegisterType((*Request)(nil), "checkout.Request")
	proto.RegisterType((*Request_Card)(nil), "checkout.Request.Card")
	proto.RegisterType((*Response)(nil), "checkout.Response")
}

func init() { proto.RegisterFile("checkout.proto", fileDescriptor_a95bdbc7e39fe4fd) }

var fileDescriptor_a95bdbc7e39fe4fd = []byte{
	// 506 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x92, 0xbd, 0x8e, 0xd4, 0x30,
	0x14, 0x85, 0x95, 0xcc, 0xef, 0x1a, 0xb4, 0xcc, 0x5a, 0x20, 0xc2, 0x08, 0x44, 0x34, 0x42, 0x02,
	0x2d, 0x4c, 0xb2, 0x3b, 0x2c, 0xcd, 0x54, 0xc0, 0x8a, 0x62, 0x91, 0x00, 0x29, 0x54, 0x14, 0x68,
	0xe4, 0x38, 0x77, 0x13, 0x33, 0x89, 0x6d, 0xfc, 0xb3, 0xcb, 0x50, 0xf2, 0x08, 0xd0, 0xd1, 0xf0,
	0x26, 0xf4, 0x14, 0x54, 0xbc, 0x02, 0x0f, 0x82, 0xe2, 0x24, 0x23, 0xa4, 0xa9, 0x72, 0xcf, 0x77,
	0xae, 0xec, 0xe3, 0xdc, 0x8b, 0xf6, 0x69, 0x01, 0x74, 0x2d, 0xac, 0x89, 0xa4, 0x12, 0x46, 0xe0,
	0x71, 0xa7, 0xa7, 0xb7, 0x73, 0x21, 0xf2, 0x12, 0x62, 0x22, 0x59, 0x4c, 0x38, 0x17, 0x86, 0x18,
	0x26, 0xb8, 0x6e, 0xfa, 0xa6, 0x8f, 0xdc, 0x87, 0xce, 0x73, 0xe0, 0x73, 0x7d, 0x49, 0xf2, 0x1c,
	0x54, 0x2c, 0xa4, 0xeb, 0xd8, 0xed, 0x9e, 0xfd, 0xf4, 0xd1, 0x28, 0x81, 0x8f, 0x16, 0xb4, 0xc1,
	0xfb, 0xc8, 0x67, 0x59, 0xe0, 0x85, 0xde, 0x83, 0xbd, 0xc4, 0x67, 0x19, 0xbe, 0x85, 0xc6, 0xa9,
	0xdd, 0x80, 0x5a, 0xb1, 0x2c, 0xf0, 0x1d, 0x1d, 0x39, 0x7d, 0x96, 0xe1, 0x3b, 0x08, 0x11, 0x4a,
	0x85, 0xe5, 0xa6, 0x36, 0x7b, 0xce, 0xdc, 0x6b, 0xc9, 0x59, 0x86, 0xaf, 0xa3, 0x81, 0x11, 0x6b,
	0xe0, 0xc1, 0xc0, 0x39, 0x8d, 0xc0, 0x77, 0xd1, 0x95, 0xe6, 0x3c, 0xa8, 0x08, 0x2b, 0x83, 0xa1,
	0xf3, 0x90, 0x43, 0x2f, 0x6a, 0x82, 0x27, 0xa8, 0x47, 0x24, 0x0b, 0x46, 0xce, 0xa8, 0xcb, 0xe9,
	0x0f, 0x0f, 0xf5, 0x4f, 0x89, 0x72, 0x59, 0x28, 0x51, 0xd9, 0x8a, 0xdb, 0xca, 0x25, 0x1c, 0x24,
	0xa3, 0x5a, 0xbf, 0xb6, 0x15, 0xbe, 0x81, 0x86, 0x19, 0x31, 0xb0, 0xaa, 0xda, 0x90, 0x83, 0x5a,
	0xbd, 0xda, 0xe2, 0x4d, 0x1b, 0xcf, 0xe1, 0x77, 0x18, 0xa3, 0x3e, 0x15, 0x19, 0x04, 0x7d, 0x77,
	0x88, 0xab, 0xeb, 0xb8, 0xe7, 0x4c, 0x69, 0xd3, 0xc5, 0x75, 0xa2, 0xee, 0x2c, 0x89, 0x36, 0x6d,
	0x4e, 0x57, 0xd7, 0x09, 0x3f, 0x33, 0xe9, 0x12, 0x0e, 0x92, 0xba, 0x9c, 0x2d, 0xd0, 0x38, 0x01,
	0x2d, 0x05, 0xd7, 0xee, 0x1c, 0x6d, 0x88, 0x81, 0xf6, 0x1f, 0x36, 0xa2, 0x7b, 0x95, 0xbf, 0x7d,
	0xd5, 0xe2, 0x3d, 0xba, 0x76, 0xda, 0x0e, 0xf3, 0x2d, 0xa8, 0x0b, 0x46, 0x01, 0xbf, 0x44, 0xe3,
	0x0e, 0xe1, 0x83, 0x68, 0x3b, 0xfa, 0x76, 0x34, 0x53, 0xfc, 0x3f, 0x6a, 0x6e, 0x9b, 0xdd, 0xfc,
	0xf2, 0xe7, 0xef, 0x37, 0xff, 0x60, 0x76, 0x35, 0xbe, 0x38, 0x8e, 0x3b, 0x7b, 0xe9, 0x1d, 0x3e,
	0xff, 0xed, 0x7d, 0x7d, 0xf6, 0xcb, 0xc3, 0x05, 0x9a, 0x74, 0x34, 0xd4, 0xcd, 0x35, 0xb3, 0x37,
	0xbb, 0x0c, 0x3f, 0x2c, 0x8c, 0x91, 0x7a, 0x19, 0xc7, 0x39, 0x33, 0x85, 0x4d, 0x23, 0x2a, 0xaa,
	0x98, 0xae, 0xd3, 0x94, 0x94, 0x65, 0xac, 0x2b, 0xab, 0xce, 0x19, 0x9f, 0x6f, 0x77, 0x6f, 0x3f,
	0x2d, 0x49, 0xf1, 0xb4, 0x20, 0x52, 0x6e, 0x22, 0xa1, 0xf2, 0x45, 0xef, 0x38, 0x3a, 0x3a, 0xf4,
	0x3d, 0x7f, 0x31, 0x21, 0x52, 0x96, 0x8c, 0xba, 0xe5, 0x8a, 0x3f, 0x68, 0xc1, 0x97, 0x3b, 0x24,
	0x79, 0x82, 0x7a, 0x27, 0x47, 0x27, 0x38, 0x42, 0xf7, 0x12, 0x30, 0x56, 0x71, 0xc8, 0xc2, 0xcb,
	0x02, 0x78, 0xa8, 0x40, 0x0b, 0xab, 0x28, 0x84, 0x99, 0x00, 0xcd, 0xef, 0x9b, 0x10, 0x3e, 0x31,
	0x6d, 0xf0, 0x10, 0xf5, 0xbf, 0xfb, 0xde, 0x28, 0x1d, 0xba, 0x55, 0x7d, 0xfc, 0x2f, 0x00, 0x00,
	0xff, 0xff, 0xc7, 0xa2, 0x79, 0x33, 0x12, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CheckoutServiceClient is the client API for CheckoutService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CheckoutServiceClient interface {
	Checkout(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type checkoutServiceClient struct {
	cc *grpc.ClientConn
}

func NewCheckoutServiceClient(cc *grpc.ClientConn) CheckoutServiceClient {
	return &checkoutServiceClient{cc}
}

func (c *checkoutServiceClient) Checkout(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/checkout.CheckoutService/Checkout", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CheckoutServiceServer is the server API for CheckoutService service.
type CheckoutServiceServer interface {
	Checkout(context.Context, *Request) (*Response, error)
}

// UnimplementedCheckoutServiceServer can be embedded to have forward compatible implementations.
type UnimplementedCheckoutServiceServer struct {
}

func (*UnimplementedCheckoutServiceServer) Checkout(ctx context.Context, req *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Checkout not implemented")
}

func RegisterCheckoutServiceServer(s *grpc.Server, srv CheckoutServiceServer) {
	s.RegisterService(&_CheckoutService_serviceDesc, srv)
}

func _CheckoutService_Checkout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CheckoutServiceServer).Checkout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/checkout.CheckoutService/Checkout",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CheckoutServiceServer).Checkout(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _CheckoutService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "checkout.CheckoutService",
	HandlerType: (*CheckoutServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Checkout",
			Handler:    _CheckoutService_Checkout_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "checkout.proto",
}
