// Code generated by protoc-gen-go. DO NOT EDIT.
// source: checkout.proto

package checkout

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	BuyerId              string   `protobuf:"bytes,2,opt,name=buyer_id,json=buyerId,proto3" json:"buyer_id,omitempty"`
	AccountId            string   `protobuf:"bytes,3,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Token                string   `protobuf:"bytes,5,opt,name=token,proto3" json:"token,omitempty"`
	BuyerEmail           string   `protobuf:"bytes,6,opt,name=buyer_email,json=buyerEmail,proto3" json:"buyer_email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_a95bdbc7e39fe4fd, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Request) GetBuyerId() string {
	if m != nil {
		return m.BuyerId
	}
	return ""
}

func (m *Request) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *Request) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *Request) GetBuyerEmail() string {
	if m != nil {
		return m.BuyerEmail
	}
	return ""
}

type Request_Card struct {
	CardNum              int32    `protobuf:"varint,1,opt,name=card_num,json=cardNum,proto3" json:"card_num,omitempty"`
	DateM                int32    `protobuf:"varint,2,opt,name=date_m,json=dateM,proto3" json:"date_m,omitempty"`
	DateY                int32    `protobuf:"varint,3,opt,name=date_y,json=dateY,proto3" json:"date_y,omitempty"`
	Code                 int32    `protobuf:"varint,4,opt,name=code,proto3" json:"code,omitempty"`
	First                string   `protobuf:"bytes,5,opt,name=first,proto3" json:"first,omitempty"`
	Last                 string   `protobuf:"bytes,6,opt,name=last,proto3" json:"last,omitempty"`
	Zip                  int32    `protobuf:"varint,7,opt,name=zip,proto3" json:"zip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request_Card) Reset()         { *m = Request_Card{} }
func (m *Request_Card) String() string { return proto.CompactTextString(m) }
func (*Request_Card) ProtoMessage()    {}
func (*Request_Card) Descriptor() ([]byte, []int) {
	return fileDescriptor_a95bdbc7e39fe4fd, []int{0, 0}
}

func (m *Request_Card) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request_Card.Unmarshal(m, b)
}
func (m *Request_Card) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request_Card.Marshal(b, m, deterministic)
}
func (m *Request_Card) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request_Card.Merge(m, src)
}
func (m *Request_Card) XXX_Size() int {
	return xxx_messageInfo_Request_Card.Size(m)
}
func (m *Request_Card) XXX_DiscardUnknown() {
	xxx_messageInfo_Request_Card.DiscardUnknown(m)
}

var xxx_messageInfo_Request_Card proto.InternalMessageInfo

func (m *Request_Card) GetCardNum() int32 {
	if m != nil {
		return m.CardNum
	}
	return 0
}

func (m *Request_Card) GetDateM() int32 {
	if m != nil {
		return m.DateM
	}
	return 0
}

func (m *Request_Card) GetDateY() int32 {
	if m != nil {
		return m.DateY
	}
	return 0
}

func (m *Request_Card) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Request_Card) GetFirst() string {
	if m != nil {
		return m.First
	}
	return ""
}

func (m *Request_Card) GetLast() string {
	if m != nil {
		return m.Last
	}
	return ""
}

func (m *Request_Card) GetZip() int32 {
	if m != nil {
		return m.Zip
	}
	return 0
}

type Response struct {
	State                string   `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_a95bdbc7e39fe4fd, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func init() {
	proto.RegisterType((*Request)(nil), "checkout.Request")
	proto.RegisterType((*Request_Card)(nil), "checkout.Request.Card")
	proto.RegisterType((*Response)(nil), "checkout.Response")
}

func init() { proto.RegisterFile("checkout.proto", fileDescriptor_a95bdbc7e39fe4fd) }

var fileDescriptor_a95bdbc7e39fe4fd = []byte{
	// 295 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x91, 0xcf, 0x4e, 0xfa, 0x40,
	0x10, 0xc7, 0x7f, 0x14, 0x4a, 0xcb, 0xfc, 0x12, 0xd4, 0x89, 0x26, 0x95, 0xc4, 0x48, 0x38, 0x79,
	0xe2, 0x20, 0x8f, 0x40, 0x34, 0xe1, 0xa0, 0x87, 0x7a, 0xf2, 0x44, 0x96, 0xdd, 0x31, 0x6e, 0xa0,
	0x5d, 0xdc, 0x3f, 0x26, 0xf8, 0x32, 0xbe, 0x80, 0x0f, 0x69, 0x76, 0xba, 0x10, 0x6f, 0xf3, 0xf9,
	0x4c, 0x3b, 0xfb, 0xcd, 0x0c, 0x8c, 0xe5, 0x3b, 0xc9, 0xad, 0x09, 0x7e, 0xbe, 0xb7, 0xc6, 0x1b,
	0x2c, 0x8f, 0x3c, 0xfb, 0xc9, 0xa0, 0xa8, 0xe9, 0x23, 0x90, 0xf3, 0x38, 0x86, 0x4c, 0xab, 0xaa,
	0x37, 0xed, 0xdd, 0x8d, 0xea, 0x4c, 0x2b, 0xbc, 0x86, 0x72, 0x13, 0x0e, 0x64, 0xd7, 0x5a, 0x55,
	0x19, 0xdb, 0x82, 0x79, 0xa5, 0xf0, 0x06, 0x40, 0x48, 0x69, 0x42, 0xeb, 0x63, 0xb3, 0xcf, 0xcd,
	0x51, 0x32, 0x2b, 0x85, 0x97, 0x90, 0x7b, 0xb3, 0xa5, 0xb6, 0xca, 0xb9, 0xd3, 0x01, 0xde, 0xc2,
	0xff, 0x6e, 0x1e, 0x35, 0x42, 0xef, 0xaa, 0x21, 0xf7, 0x80, 0xd5, 0x43, 0x34, 0x93, 0xef, 0x1e,
	0x0c, 0x96, 0xc2, 0xf2, 0xcb, 0x52, 0x58, 0xb5, 0x6e, 0x43, 0xc3, 0x79, 0xf2, 0xba, 0x88, 0xfc,
	0x1c, 0x1a, 0xbc, 0x82, 0xa1, 0x12, 0x9e, 0xd6, 0x0d, 0x47, 0xca, 0xeb, 0x3c, 0xd2, 0xd3, 0x49,
	0x1f, 0x38, 0x4c, 0xd2, 0xaf, 0x88, 0x30, 0x90, 0x46, 0x51, 0x35, 0x60, 0xc9, 0x75, 0x0c, 0xf7,
	0xa6, 0xad, 0xf3, 0xc7, 0x70, 0x0c, 0xf1, 0xcb, 0x9d, 0x70, 0x3e, 0xa5, 0xe2, 0x1a, 0xcf, 0xa1,
	0xff, 0xa5, 0xf7, 0x55, 0xc1, 0x3f, 0xc7, 0x72, 0x36, 0x85, 0xb2, 0x26, 0xb7, 0x37, 0xad, 0xe3,
	0x39, 0xce, 0x0b, 0x4f, 0x69, 0x63, 0x1d, 0xdc, 0x3f, 0xc2, 0xd9, 0x32, 0x2d, 0xf7, 0x85, 0xec,
	0xa7, 0x96, 0x84, 0x0b, 0x28, 0x8f, 0x0a, 0x2f, 0xe6, 0xa7, 0x53, 0xa4, 0xb5, 0x4f, 0xf0, 0xaf,
	0xea, 0x66, 0xcf, 0xfe, 0x6d, 0x86, 0x7c, 0xa9, 0xc5, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xdb,
	0x65, 0xc3, 0x9f, 0xbb, 0x01, 0x00, 0x00,
}
